### ISSUE TITLE
Ubuntu apt-get install extremely slow download in EU Ireland region

### ISSUE THREAD

**Issue by lioramilbaum** [agileorbit-cookbooks/java#389] opened 2016-12-06 07:11 UTC
Please provide the ability to change the apt-get resource list to speed up the installation.

**Comment by erichelgeson** [comment] 2016-12-06 13:46
This is a duplicate of https://github.com/agileorbit-cookbooks/java/issues/387

**Closed by erichelgeson** 2016-12-06 13:46 UTC
