### ISSUE TITLE
install of oracle java 8 fails

### ISSUE THREAD

**Issue by jjdevbiz** [agileorbit-cookbooks/java#292] opened 2015-09-16 19:45 UTC
```
       Recipe: java::oracle
         * java_ark[jdk] action install
           - create dir /usr/lib/jvm and change owner to root
           * yum_package[curl] action install (up to date)
           - download oracle tarball straight from the server[2015-09-16T19:43:42+00:00] FATAL: Failed to extract file jdk-8u20-linux-x64.tar.gz!
       
           ================================================================================
           Error executing action `install` on resource 'java_ark[jdk]'
           ================================================================================
           
           SystemExit
           ----------
           exit
       
           Cookbook Trace:
       ---------------
           /tmp/kitchen/cache/cookbooks/java/providers/ark.rb:159:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/java/providers/ark.rb:137:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/java/recipes/oracle.rb
           
        53: java_ark "jdk" do
        54:   url tarball_url
        55:   default node['java']['set_default']
        56:   checksum tarball_checksum
        57:   app_home java_home
        58:   bin_cmds bin_cmds
        59:   alternatives_priority node['java']['alternatives_priority']
        60:   retries node['java']['ark_retries']
        61:   retry_delay node['java']['ark_retry_delay']
            62:   action :install
        63: end
       
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/java/recipes/oracle.rb:53:in `from_file'
           
           java_ark("jdk") do
         action [:install]
         supports {:report=>true, :exception=>true}
             retries 0
             retry_delay 2
       
       
         cookbook_name "java"
         recipe_name "oracle"
             url "http://download.oracle.com/otn-pub/java/jdk/8u20-b26/jdk-8u20-linux-x64.tar.gz"
             default true
             checksum "ec7f89dc3697b402e2c851d0488f6299"
             app_home "/usr/lib/jvm/java"
             bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconso
le", "jcontrol", "jdb", "jdeps", "jhat", "jinfo", "jjs", "jmap", "jmc", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200
", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
         alternatives_priority 1062
         owner "root"
         app_home_mode 493
       end
           
       
       Running handlers:
       [2015-09-16T19:43:42+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-09-16T19:43:42+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 87.962972876 seconds
       [2015-09-16T19:43:42+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-09-16T19:43:42+00:00] ERROR: java_ark[jdk] (java::oracle line 53) had an error: SystemExit: exit
       [2015-09-16T19:43:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <install-java-centos-66>.
>>>>>> Please see .kitchen/logs/install-java-centos-66.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------
```

**Comment by erichelgeson** [comment] 2015-09-16 19:48
The error is it looks like the file downloaded was invalid: `FATAL: Failed to extract file jdk-8u20-linux-x64.tar.gz!`

Can you look at that file, maybe there is a proxy or a 404 or something. Also please try the latest version of the cookbook.

**Comment by rich-murray** [comment] 2015-09-22 15:51
Hi I'm getting the same error trying to install Oracle Java 8.  The following output is from a Ubuntu 14.04 machine using version 1.35.0 of the Java cookbook (using Chef solo, Vagrant & Berkshelf).  The download URL for the JDK is pointing at an internal server, and is a file I have installed via Chef several times before so I'm not sure why I'm suddenly getting the error
```
"[2015-09-22T15:37:59+00:00] FATAL: Failed to extract file jdk-8u51-linux-x64.tar.gz!"
```
I can manually get this file and extract it without any problems.

```
==> default: Recipe: java::oracle
==> default:   
==> default: * apt_package[tar] action install
==> default:  (up to date)
==> default:   * java_ark[jdk] action install[2015-09-22T15:37:52+00:00] INFO: Adding jdk to /usr/lib/jvm/jdk1.8.0_51
==> default:     
==> default: - create dir /usr/lib/jvm and change owner to root:root
==> default:     
==> default: * remote_file[/var/chef/cache/jdk-8u51-linux-x64.tar.gz] action create_if_missing
==> default:  (up to date)
==> default: [2015-09-22T15:37:59+00:00] FATAL: Failed to extract file jdk-8u51-linux-x64.tar.gz!
==> default:     
==> default: 
==> default:     
==> default: ================================================================================
==> default:     
==> default: Error executing action `install` on resource 'java_ark[jdk]'
==> default: 
==> default:     ================================================================================
==> default:     
==> default:     SystemExit
==> default:     ----------
==> default:     exit
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /tmp/vagrant-chef/b563a96bf700ed7ab537abaa79ec9e01/cookbooks/java/providers/ark.rb:164:in `block (2 levels) in class_from_file'
==> default:     /tmp/vagrant-chef/b563a96bf700ed7ab537abaa79ec9e01/cookbooks/java/providers/ark.rb:142:in `block in class_from_file'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /tmp/vagrant-chef/b563a96bf700ed7ab537abaa79ec9e01/cookbooks/java/recipes/oracle.rb
==> default:     
==> default:      55: java_ark "jdk" do
==> default:      56:   url tarball_url
==> default:      57:   default node['java']['set_default']
==> default:      58:   checksum tarball_checksum
==> default:      59:   app_home java_home
==> default:      60:   bin_cmds bin_cmds
==> default:      61:   alternatives_priority node['java']['alternatives_priority']
==> default:      62:   retries node['java']['ark_retries']
==> default:     
==> default:  63:   retry_delay node['java']['ark_retry_delay']
==> default: 
==> default:     
==> default:  64:   connect_timeout node['java']['ark_timeout']
==> default: 
==> default:     
==> default:  65:   use_alt_suffix node['java']['use_alt_suffix']
==> default: 
==> default:     
==> default:  66:   reset_alternatives node['java']['reset_alternatives']
==> default:      67:   action :install
==> default:      68: end
==> default:      69: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /tmp/vagrant-chef/b563a96bf700ed7ab537abaa79ec9e01/cookbooks/java/recipes/oracle.rb:55:in `from_file'
==> default:     
==> default:     java_ark("jdk") do
==> default:       action [:install]
==> default:       supports {:report=>true, :exception=>true}
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :java_ark
==> default:       cookbook_name :java
==> default:       recipe_name "oracle"
==> default:       url "http://bpm-ci-repos:8650/downloads/java/jdk/jdk-8u51-linux-x64.tar.gz"
==> default:       default true
==> default:       checksum "d7149012cc51c2cdb8d3a1767825e0dfc36ca0419c3dae56d993cb2732cbeff1"
==> default:       app_home "/usr/lib/jvm/java-8-oracle-amd64"
==> default:       bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jdeps", "jhat", "jinfo", "jjs", "jmap", "jmc", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
==> default:       alternatives_priority 1062
==> default:       connect_timeout 600
==> default:       use_alt_suffix true
==> default:       reset_alternatives true
==> default:       owner "root"
==> default:       app_home_mode 493
==> default:     end
==> default:     
==> default: [2015-09-22T15:37:59+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2015-09-22T15:37:59+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2015-09-22T15:37:59+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 2 resources updated in 12.205882728 seconds
==> default: [2015-09-22T15:37:59+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-09-22T15:37:59+00:00] ERROR: java_ark[jdk] (java::oracle line 55) had an error: SystemExit: exit
==> default: [2015-09-22T15:37:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by rich-murray** [comment] 2015-09-22 16:19
Here's some additional output with DEBUG logging on:

```
==> default: * apt_package[tar] action install
==> default: [2015-09-22T16:04:42+00:00] INFO: Processing apt_package[tar] action install (java::oracle line 53)
==> default: [2015-09-22T16:04:42+00:00] DEBUG: Providers for generic apt_package resource enabled on node include: [Chef::Provider::Package::Apt]
==> default: [2015-09-22T16:04:42+00:00] DEBUG: Provider for action install on resource apt_package[tar] is Chef::Provider::Package::Apt
==> default: [2015-09-22T16:04:45+00:00] DEBUG: apt_package[tar] current version is 1.27.1-1
==> default: [2015-09-22T16:04:45+00:00] DEBUG: apt_package[tar] candidate version is 1.27.1-1
==> default: [2015-09-22T16:04:45+00:00] DEBUG: apt_package[tar] tar 1.27.1-1 already installed
==> default: [2015-09-22T16:04:45+00:00] DEBUG: apt_package[tar] is already installed - nothing to do
==> default:  (up to date)
==> default:   * java_ark[jdk] action install[2015-09-22T16:04:45+00:00] INFO: Processing java_ark[jdk] action install (java::oracle line 55)
==> default: [2015-09-22T16:04:45+00:00] DEBUG: Providers for generic java_ark resource enabled on node include: [LWRP provider java_ark from cookbook java]
==> default: [2015-09-22T16:04:45+00:00] DEBUG: Provider for action install on resource java_ark[jdk] is LWRP provider java_ark from cookbook java
==> default: [2015-09-22T16:04:45+00:00] INFO: Adding jdk to /usr/lib/jvm/jdk1.8.0_51
==> default:     
==> default: - create dir /usr/lib/jvm and change owner to root:root
==> default: [2015-09-22T16:04:45+00:00] DEBUG: downloading tarball from an unofficial repository
==> default: [2015-09-22T16:04:45+00:00] DEBUG: Resources for generic remote_file resource enabled on node include: [Chef::Resource::RemoteFile]
==> default: [2015-09-22T16:04:45+00:00] DEBUG: Resource for remote_file is Chef::Resource::RemoteFile
==> default:     
==> default: * remote_file[/var/chef/cache/jdk-8u51-linux-x64.tar.gz] action create_if_missing
==> default: [2015-09-22T16:04:45+00:00] INFO: Processing remote_file[/var/chef/cache/jdk-8u51-linux-x64.tar.gz] action create_if_missing (/tmp/vagrant-chef/b4ead896ad0501e798cba86bb66abf22/cookbooks/java/providers/ark.rb line 128)
==> default: [2015-09-22T16:04:45+00:00] DEBUG: remote_file[/var/chef/cache/jdk-8u51-linux-x64.tar.gz] checksumming file at /var/chef/cache/jdk-8u51-linux-x64.tar.gz.
==> default: [2015-09-22T16:04:46+00:00] DEBUG: remote_file[/var/chef/cache/jdk-8u51-linux-x64.tar.gz] exists at /var/chef/cache/jdk-8u51-linux-x64.tar.gz taking no action.
==> default:  (up to date)
==> default: [2015-09-22T16:04:52+00:00] FATAL: Failed to extract file jdk-8u51-linux-x64.tar.gz!
```

If I ssh onto the machine I can see the file has been downloaded OK.  It also looks as if it has been extracted:

```
vagrant@vagrant:~$ ls -ltr /var/chef/cache/
total 346240
drwxr-xr-x 1 vagrant vagrant      4096 Jun  9 02:40 jdk1.8.0_51
drwxr-xr-x 1 vagrant vagrant      4096 Aug  4 19:32 jdk1.8.0_60
-rwxr-xr-x 1 vagrant vagrant 173281904 Sep  9 15:20 jdk-8u51-linux-x64.tar.gz
-rwxr-xr-x 1 vagrant vagrant 181238643 Sep 18 15:28 jdk-8u60-linux-x64.tar.gz
drwxr-xr-x 1 vagrant vagrant      4096 Sep 18 15:28 remote_file
-rw-r--r-- 1 vagrant vagrant         4 Sep 22 16:12 chef-client-running.pid
-rw-r----- 1 vagrant vagrant      4480 Sep 22 16:12 chef-stacktrace.out
```

I'm not sure why I see 2 JDKs here though.  I did try updating to use the latest 8u60 but got the same error, so have reverted back to 8u51 (I have destroyed and re-created the VM I'm using since them so I don't know where 8u60 is coming from).

Thanks, Rich.

**Comment by haggy** [comment] 2015-09-23 15:40
Im having this exact same issue. I put some debug statements into the `ark.rb` file (which does the extraction) and the error I get is:
`tar: jdk1.8.0_51/jre/lib/amd64/server/libjsig.so: Cannot create symlink to ‘../libjsig.so’: Protocol error`

If I login to that box and extract that to my home directory it works but anywhere within the `/var/chef/cache` directory will fail.

Stats:
```
Host OS: Mac OSX
VM: Ubuntu
VBox version: 5.0.4r102546
```

**Comment by cheeseplus** [comment] 2015-09-23 16:18
Is the location of the /var/chef/cache folder mapped to a shared drive (either network or host based)? That tar error is usually related to trying to create symlinks on filesystems that don't support it.

**Comment by haggy** [comment] 2015-09-23 16:33
I checked in VirtualBox manager UI under Settings and I did not see anything specific to that directory. 

![image](https://cloud.githubusercontent.com/assets/2634904/10051379/25164c7c-61ef-11e5-95bb-7ab199db84cb.png)

Is `vagrant-cache` the `/var/chef/cache`? I didn't think it was.

**Comment by shane-axiom** [comment] 2015-09-23 20:20
I ran into this while using [vagrant-cachier](http://fgrehm.viewdocs.io/vagrant-cachier/) in `machine` mode, which creates a shared folder mapped to `/tmp/vagrant-cache` (`var/chef/cache` is symlinked to `/tmp/vagrant-cache`). Symlink creation in shared folders is disabled by default in VirtualBox.

Disabling the use of `vagrant-cachier` solved for me, which is unfortunate. Supposedly you can also fix by adding the following to the provider config in `Vagrantfile`:

    config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/NAMEOFSHAREDFOLDER", "1"]

But I tried with both `vagrant-cache` and `/tmp/vagrant-cache` without success. Others may want to experiment with that (and please report here if you get it working).

**Comment by rich-murray** [comment] 2015-09-24 09:35
Hi, how did you disable vagrant-cachier?  I've commented out the vagrant-cachier settings in my Vagrantfile (I had mine set to box scope) but I'm still getting an error.   The error is slightly different now though:

```
==> default: [2015-09-24T08:52:03+00:00] ERROR: java_ark[jdk] (java::oracle line 55) had an error: Chef::Exceptions::ContentLengthMismatch: remote_file[/var/chef/cache/jdk-8u60-linux-x64.tar.gz] (/tmp/vagrant-chef/ca99f4779cc2defb3d150963ee41c5b4/cookbooks/java/providers/ark.rb line 128) had an error: Chef::Exceptions::ContentLengthMismatch: Response body length 73725792 does not match HTTP Content-Length header 181238643.
==> default: [2015-09-24T08:52:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I've tried a couple of versions of Java (1.8.0.51 and 1.8.0.60) and I get the same sort of the error.  The .tar.gz for Java 1.8.0.51 is on an internal server and has been installed several times before using Chef. so I'm confused by this error.

I'm running Chef 12.4.3.

**Comment by cheeseplus** [comment] 2015-09-24 12:23
Content Length mismatches can be due to double compression from the HTTP server that is serving up the tarball, see https://github.com/agileorbit-cookbooks/java/issues/225#issuecomment-69082316

**Comment by kotowick** [comment] 2015-09-29 19:28
Was this fixed? Getting the same issue.

**Comment by haggy** [comment] 2015-09-29 21:03
I "got around" this by modifying the chef file cache path... In my vagrant file:
```
chef.file_cache_path = '/chef-cache/main-cache'
```

The path can be anything but I kept it as descriptive as possible.

**Comment by cheeseplus** [comment] 2015-09-29 22:15
The root issue seems to be the use of vagrant-cachier because of how it maps shared folders and the fact that tar can't create a symlink - so the work around is specifically in the case you're using this setup and doesn't appear to be an issue with the cookbook itself.

At best the cookbook could extract the file in a different place, though that breaks with the convention of using the cache, but I don't think that it could auto-detect if vagrant-cachier is in play. To me this isn't an issue with the cookbook itself but an issue created by the use of vagrant-cachier.

**Comment by spuder** [comment] 2015-11-13 18:01
The following test kitchen works with oracle 8 here: 

Vagrant 1.7.4
Virtualbox 5.0.4r102546
Chef Development Kit Version: 0.9.0


```
---
driver:
  name: vagrant
  network:
  - ["forwarded_port", { guest: 8081, host: 8081 }]

platforms:
  - name: ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[java]
  attributes:
    java:
      install_flavor: "oracle"
      jdk_version: "8"
      oracle:
        accept_oracle_download_terms: true
```

**Comment by rich-murray** [comment] 2015-11-25 15:10
I'm still getting a ContentLengthMismatch error when using a local http server to retrieve the download (it seems to work OK pointing at the Oracle site)
```
==> default: Chef::Exceptions::ContentLengthMismatch
==> default:     ---------------------------------------
==> default:     remote_file[/chef-cache/main-cache/jdk-8u51-linux-x64.tar.gz] (/tmp/vagrant-chef/617bbc9ef483c1de5d5253a56c109f42/cookbooks/java/providers/ark.rb line 129) had an error: Chef::Exceptions::ContentLengthMismatch: Response body length 73180472 does not match HTTP Content-Length header 173281904.
```

I have uninstalled vagrant-cachier.
I have also tried setting chef.file_cache_path in my Vagrantfile
I've tried amended the config for nginx so gzip is off.

None of these have worked.  If this is due to "double compression from the HTTP server" can anyone advise how to fix this (with nginx).

**Comment by erichelgeson** [comment] 2016-07-20 14:25
Closing as not a bug with this cookbook.

**Closed by erichelgeson** 2016-07-20 14:25 UTC
