### ISSUE TITLE
cookbook not able to install oracle jdk, hangs during download from oracle

### ISSUE THREAD

**Issue by stantonk** [agileorbit-cookbooks/java#313] opened 2015-11-04 17:48 UTC
On a Vagrant box, provisioned with java cookbook:

```
==> default: [2015-11-04T17:39:50+00:00] INFO: Adding jdk to /usr/lib/jvm/jdk1.7.0_75_alt
==> default: [2015-11-04T17:39:50+00:00] INFO: Processing package[curl] action install (/tmp/vagrant-chef/2897aea8097e903c2ce281330b6646fe/cookbooks/java/providers/ark.rb line 72)
```

I haven't been able to successfully install the Oracle JDK for almost 2 weeks now.

Seeing this:

```
==> default: [2015-11-04T16:58:00+00:00] ERROR: java_ark[jdk] (svc::default line 26) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
==> default: Command exceeded allowed execution time, process terminated
==> default: ---- Begin output of  curl --create-dirs -L --retry 0 --retry-delay 2 --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u67-b01/jdk-7u67-linux-x64.tar.gz -o /var/chef/cache/jdk-7u67-linux-x64.tar.gz  ----
```

I have tried the latest version of the cookbook to no avail.

Any suggestions here?

**Comment by stantonk** [comment] 2015-11-04 17:51
bizzarely, i can download it outside of chef w/ the same curl no problem:

```
$ curl --create-dirs -L --retry 0 --retry-delay 2 --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u67-b01/jdk-7u67-linux-x64.tar.gz -o ./jdk-7u67-linux-x64.tar.gz  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   288  100   288    0     0    215      0  0:00:01  0:00:01 --:--:--  1846
100  135M  100  135M    0     0  3486k      0  0:00:39  0:00:39 --:--:-- 4548k
$ ll
total 278080
-rw-r--r--  1 stantonk  staff   136M Nov  4 11:49 jdk-7u67-linux-x64.tar.gz
```

**Comment by stantonk** [comment] 2015-11-04 17:59
Also works fine in a vanilla ubuntu VM doing the curl manually.

```
vagrant@vagrant-ubuntu-trusty-64:~$ curl --create-dirs -L --retry 0 --retry-delay 2 --cookie "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u67-b01/jdk-7u67-linux-x64.tar.gz -o ./jdk-7u67-linux-x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   288  100   288    0     0    545      0 --:--:-- --:--:-- --:--:--   862
100  135M  100  135M    0     0  2577k      0  0:00:53  0:00:53 --:--:-- 2981k
```

**Comment by erichelgeson** [comment] 2015-11-04 21:41
Environment vars? same user? Proxy? I'd try putting the file on a local mirror so you don't have to rely on oracle as well

**Comment by stantonk** [comment] 2015-11-05 06:43
@erichelgeson env vars / user / proxy haven't changed since it worked. local mirror fixes issue of course. ¯\_(ツ)_/¯

**Comment by erichelgeson** [comment] 2015-11-05 15:31
Ya, unsure... I've seen others have the issue but I'm unable to reproduce or their issue goes away after a few days. If you do find something please let us know. I just ran the whole test kitchen suite and downloaded it from oracle ~10x without issue.

**Comment by stantonk** [comment] 2015-11-17 04:20
@cswingler didn't you figure anything out on this?

**Comment by cswingler** [comment] 2015-11-17 22:15
@stantonk not really, it just sort of randomly doesn't work. My speculation is that Oracle eventually just blacklists you if you download things too many times in a period of time, but I've been able to download from Oracle reliably for the past two weeks.

**Comment by eyalzek** [comment] 2016-07-14 12:45
I have to change the "connect_timeout" attribute to a minimum of 900 seconds for it to sometimes work...
I tried to create a vagrant box which already provisions the java installation (that's the biggest bottleneck when testing locally with kitchen), but even when the package is installed, the java steps takes a few minutes until it realizes it's already installed.
Might be that it's downloading the package all over again for some reason....

**Comment by toddlers** [comment] 2016-11-11 07:35
We have faced this issue yesterday where java recipe for oracle-java install was failing.

Seems like an issue from Oracle side . It started working after 8-10 hours.

We are changing the oracle-java install recipe to pull java binary from s3 .

**Comment by erichelgeson** [comment] 2016-11-11 15:22
This hasnt really been an issue (client side) lately so i'm going to close this. Oracle will always have outages so hosting your binaries on S3 or artifactory is the best.

**Closed by erichelgeson** 2016-11-11 15:22 UTC
